add_files -norecurse rsd/Processor/Src/MicroArchConf.sv

add_files -norecurse rsd/Processor/Src/BasicMacros.sv
add_files -norecurse rsd/Processor/Src/BasicTypes.sv
add_files -norecurse rsd/Processor/Src/IO/IO_UnitTypes.sv
add_files -norecurse rsd/Processor/Src/Memory/MemoryMapTypes.sv
add_files -norecurse rsd/Processor/Src/Debug/DebugTypes.sv
add_files -norecurse rsd/Processor/Src/RegisterFile/BypassTypes.sv
add_files -norecurse rsd/Processor/Src/Pipeline/PipelineTypes.sv
add_files -norecurse rsd/Processor/Src/RenameLogic/RenameLogicTypes.sv
add_files -norecurse rsd/Processor/Src/RenameLogic/ActiveListIndexTypes.sv
add_files -norecurse rsd/Processor/Src/Scheduler/SchedulerTypes.sv
add_files -norecurse rsd/Processor/Src/Privileged/CSR_UnitTypes.sv
add_files -norecurse rsd/Processor/Src/FetchUnit/FetchUnitTypes.sv
add_files -norecurse rsd/Processor/Src/LoadStoreUnit/LoadStoreUnitTypes.sv
add_files -norecurse rsd/Processor/Src/Memory/MemoryTypes.sv
add_files -norecurse rsd/Processor/Src/Cache/CacheSystemTypes.sv
add_files -norecurse rsd/Processor/Src/FloatingPointUnit/FPUTypes.sv

add_files -norecurse rsd/Processor/Src/Controller.sv
add_files -norecurse rsd/Processor/Src/ExecUnit/MultiplierUnit.sv
add_files -norecurse rsd/Processor/Src/ExecUnit/PipelinedRefDivider.sv
add_files -norecurse rsd/Processor/Src/ExecUnit/BitCounter.sv
add_files -norecurse rsd/Processor/Src/ExecUnit/Shifter.sv
add_files -norecurse rsd/Processor/Src/ExecUnit/DividerUnit.sv
add_files -norecurse rsd/Processor/Src/ExecUnit/IntALU.sv
add_files -norecurse rsd/Processor/Src/MulDivUnit/MulDivUnitIF.sv
add_files -norecurse rsd/Processor/Src/MulDivUnit/MulDivUnit.sv
add_files -norecurse rsd/Processor/Src/IO/IO_Unit.sv
add_files -norecurse rsd/Processor/Src/IO/IO_UnitIF.sv
add_files -norecurse rsd/Processor/Src/Debug/PerformanceCounter.sv
add_files -norecurse rsd/Processor/Src/Debug/PerformanceCounterIF.sv
add_files -norecurse rsd/Processor/Src/Debug/DebugIF.sv
add_files -norecurse rsd/Processor/Src/Debug/Debug.sv
add_files -norecurse rsd/Processor/Src/RegisterFile/RegisterFileIF.sv
add_files -norecurse rsd/Processor/Src/RegisterFile/BypassNetwork.sv
add_files -norecurse rsd/Processor/Src/RegisterFile/BypassNetworkIF.sv
add_files -norecurse rsd/Processor/Src/RegisterFile/RegisterFile.sv
add_files -norecurse rsd/Processor/Src/RegisterFile/BypassController.sv
add_files -norecurse rsd/Processor/Src/Main.sv
add_files -norecurse rsd/Processor/Src/Verification/TestMain.sv
add_files -norecurse rsd/Processor/Src/Verification/TestBenchClockGenerator.sv
add_files -norecurse rsd/Processor/Src/Verification/Dumper.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/SourceCAM/TestSourceCAM.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/SourceCAM/TestSourceCAM_Top.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/DistributedDualPortRAM/TestDistributedDualPortRAM_Top.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/DistributedDualPortRAM/TestDistributedDualPortRAM.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/DistributedMultiBankRAM/TestDistributedMultiBankRAM_Top.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/RegisterFile/TestRegisterFileTop.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/RegisterFile/TestRegisterFile.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/ICache/TestICacheTop.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/ICache/TestICache.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/DCacheFiller/TestDCacheFiller.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/DCacheFiller/TestDCacheFillerTop.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/BlockMultiPortRAM/TestBlockMultiPortRAM.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/BlockMultiPortRAM/TestBlockMultiPortRAM_Top.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/DistributedSharedMultiPortRAM/TestDistributedSharedMultiPortRAM_Top.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/ICacheSystem/TestICacheSystem.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/ICacheSystem/TestICacheSystemTop.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/BlockDualPortRAM/TestBlockDualPortRAM.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/BlockDualPortRAM/TestBlockDualPortRAM_Top.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/DistributedSinglePortRAM/TestDistributedSinglePortRAM_Top.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/Divider/TestDivider.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/Divider/RefDivider.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/Divider/TestDividerTop.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/RegisterMultiPortRAM/TestRegisterMultiPortRAM_Top.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/MultiWidthFreeList/TestMultiWidthFreeList.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/MultiWidthFreeList/TestMultiWidthFreeListTop.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/CacheSystem/TestCacheSystemTop.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/CacheSystem/TestCacheSystem.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/DRAM_Controller/TestDRAM_Controller.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/DRAM_Controller/TestDRAM_ControllerTop.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/MultiWidthQueuePointer/TestMultiWidthQueuePointer.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/MultiWidthQueuePointer/TestMultiWidthQueuePointerTop.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/ICacheFiller/TestICacheFiller.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/ICacheFiller/TestICacheFillerTop.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/Memory/TestMemoryTop.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/Memory/TestMemory.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/LRU_Counter/TestLRU_Counter.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/LRU_Counter/TestLRU_CounterTop.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/DistributedMultiPortRAM/TestDistributedMultiPortRAM_Top.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/DistributedMultiPortRAM/TestDistributedMultiPortRAM.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/InitializedBlockRAM/TestInitializedBlockRAM_Top.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/DCache/TestDCache.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/DCache/TestDCacheTop.sv
add_files -norecurse rsd/Processor/Src/Verification/UnitTest/BlockTrueDualPortRAM/TestBlockTrueDualPortRAM_Top.sv
add_files -norecurse rsd/Processor/Src/Verification/TestIntALU.sv
add_files -norecurse rsd/Processor/Src/Pipeline/CommitStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/FPBackEnd/FPRegisterWriteStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/FPBackEnd/FPExecutionStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/FPBackEnd/FPRegisterReadStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/FPBackEnd/FPRegisterReadStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/FPBackEnd/FPIssueStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/FPBackEnd/FPExecutionStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/FPBackEnd/FPIssueStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/ComplexIntegerBackEnd/ComplexIntegerRegisterReadStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/ComplexIntegerBackEnd/ComplexIntegerIssueStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/ComplexIntegerBackEnd/ComplexIntegerIssueStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/ComplexIntegerBackEnd/ComplexIntegerRegisterReadStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/ComplexIntegerBackEnd/ComplexIntegerExecutionStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/ComplexIntegerBackEnd/ComplexIntegerExecutionStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/ComplexIntegerBackEnd/ComplexIntegerRegisterWriteStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryAccessStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryTagAccessStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryRegisterWriteStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryExecutionStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryIssueStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryExecutionStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryAccessStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryTagAccessStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryRegisterReadStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryRegisterReadStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryIssueStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/MemoryBackEnd/MemoryRegisterWriteStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/ScheduleStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/RenameStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/RenameStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/IntegerBackEnd/IntegerRegisterWriteStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/IntegerBackEnd/IntegerIssueStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/IntegerBackEnd/IntegerRegisterReadStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/IntegerBackEnd/IntegerExecutionStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/IntegerBackEnd/IntegerExecutionStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/IntegerBackEnd/IntegerIssueStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/IntegerBackEnd/IntegerRegisterWriteStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/IntegerBackEnd/IntegerRegisterReadStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/DispatchStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/CommitStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/PreDecodeStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/DecodeStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/DecodeStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/PreDecodeStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/FetchStage/FetchStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/FetchStage/FetchStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/FetchStage/NextPCStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/FetchStage/NextPCStage.sv
add_files -norecurse rsd/Processor/Src/Pipeline/FetchStage/PC.sv
add_files -norecurse rsd/Processor/Src/Pipeline/ScheduleStageIF.sv
add_files -norecurse rsd/Processor/Src/Pipeline/DispatchStage.sv
add_files -norecurse rsd/Processor/Src/ResetController.sv
add_files -norecurse rsd/Processor/Src/Main_Zynq.sv
add_files -norecurse rsd/Processor/Src/ControllerIF.sv
add_files -norecurse rsd/Processor/Src/RenameLogic/RenameLogic.sv
add_files -norecurse rsd/Processor/Src/RenameLogic/ActiveList.sv
add_files -norecurse rsd/Processor/Src/RenameLogic/RMT.sv
add_files -norecurse rsd/Processor/Src/RenameLogic/RenameLogicCommitter.sv
add_files -norecurse rsd/Processor/Src/RenameLogic/ActiveListIF.sv
add_files -norecurse rsd/Processor/Src/RenameLogic/RetirementRMT.sv
add_files -norecurse rsd/Processor/Src/RenameLogic/RenameLogicIF.sv
add_files -norecurse rsd/Processor/Src/Primitives/RAM_Vivado.sv
add_files -norecurse rsd/Processor/Src/Primitives/RAM_Synplify.sv
add_files -norecurse rsd/Processor/Src/Primitives/RAM.sv
add_files -norecurse rsd/Processor/Src/Primitives/Multiplier.sv
add_files -norecurse rsd/Processor/Src/Primitives/FreeList.sv
add_files -norecurse rsd/Processor/Src/Primitives/LRU_Counter.sv
add_files -norecurse rsd/Processor/Src/Primitives/FlipFlop.sv
add_files -norecurse rsd/Processor/Src/Primitives/Divider.sv
add_files -norecurse rsd/Processor/Src/Primitives/Picker.sv
add_files -norecurse rsd/Processor/Src/Primitives/Queue.sv
add_files -norecurse rsd/Processor/Src/LoadStoreUnit/LoadStoreUnitIF.sv
add_files -norecurse rsd/Processor/Src/LoadStoreUnit/LoadQueue.sv
add_files -norecurse rsd/Processor/Src/LoadStoreUnit/StoreQueue.sv
add_files -norecurse rsd/Processor/Src/LoadStoreUnit/StoreCommitter.sv
add_files -norecurse rsd/Processor/Src/LoadStoreUnit/LoadStoreUnit.sv
add_files -norecurse rsd/Processor/Src/FetchUnit/BTB.sv
add_files -norecurse rsd/Processor/Src/FetchUnit/Gshare.sv
add_files -norecurse rsd/Processor/Src/FetchUnit/BranchPredictor.sv
add_files -norecurse rsd/Processor/Src/FetchUnit/Bimodal.sv
add_files -norecurse rsd/Processor/Src/Main_Fpga.sv
add_files -norecurse rsd/Processor/Src/Main_Zynq_Wrapper.sv
add_files -norecurse rsd/Processor/Src/Privileged/CSR_Unit.sv
add_files -norecurse rsd/Processor/Src/Privileged/InterruptController.sv
add_files -norecurse rsd/Processor/Src/Privileged/CSR_UnitIF.sv
add_files -norecurse rsd/Processor/Src/SysDeps/Verilator/VerilatorHelper.sv
add_files -norecurse rsd/Processor/Src/Recovery/RecoveryManagerIF.sv
add_files -norecurse rsd/Processor/Src/Recovery/RecoveryManager.sv
add_files -norecurse rsd/Processor/Src/Memory/ControlQueue.sv
add_files -norecurse rsd/Processor/Src/Memory/Axi4LiteControlRegisterIF.sv
add_files -norecurse rsd/Processor/Src/Memory/Memory.sv
add_files -norecurse rsd/Processor/Src/Memory/Axi4Memory.sv
add_files -norecurse rsd/Processor/Src/Memory/Axi4LiteControlMemoryIF.sv
add_files -norecurse rsd/Processor/Src/Memory/MemoryReadReqQueue.sv
add_files -norecurse rsd/Processor/Src/Memory/MemoryLatencySimulator.sv
add_files -norecurse rsd/Processor/Src/Memory/MemoryWriteDataQueue.sv
add_files -norecurse rsd/Processor/Src/Memory/Axi4LiteMemory.sv
add_files -norecurse rsd/Processor/Src/Memory/Axi4MemoryIF.sv
add_files -norecurse rsd/Processor/Src/Memory/Axi4LiteControlRegister.sv
add_files -norecurse rsd/Processor/Src/SynthesisMacros.sv
add_files -norecurse rsd/Processor/Src/Core.sv
add_files -norecurse rsd/Processor/Src/Scheduler/ReplayQueue.sv
add_files -norecurse rsd/Processor/Src/Scheduler/IssueQueue.sv
add_files -norecurse rsd/Processor/Src/Scheduler/SourceCAM.sv
add_files -norecurse rsd/Processor/Src/Scheduler/WakeupSelectIF.sv
add_files -norecurse rsd/Processor/Src/Scheduler/ReadyBitTable.sv
add_files -norecurse rsd/Processor/Src/Scheduler/SchedulerIF.sv
add_files -norecurse rsd/Processor/Src/Scheduler/SelectLogic.sv
add_files -norecurse rsd/Processor/Src/Scheduler/ProducerMatrix.sv
add_files -norecurse rsd/Processor/Src/Scheduler/WakeupPipelineRegister.sv
add_files -norecurse rsd/Processor/Src/Scheduler/MemoryDependencyPredictor.sv
add_files -norecurse rsd/Processor/Src/Scheduler/WakeupLogic.sv
add_files -norecurse rsd/Processor/Src/Scheduler/Scheduler.sv
add_files -norecurse rsd/Processor/Src/Scheduler/DestinationRAM.sv
add_files -norecurse rsd/Processor/Src/Cache/CacheFlushManagerIF.sv
add_files -norecurse rsd/Processor/Src/Cache/ICache.sv
add_files -norecurse rsd/Processor/Src/Cache/DCache.sv
add_files -norecurse rsd/Processor/Src/Cache/CacheSystemIF.sv
add_files -norecurse rsd/Processor/Src/Cache/MemoryAccessController.sv
add_files -norecurse rsd/Processor/Src/Cache/DCacheIF.sv
add_files -norecurse rsd/Processor/Src/Cache/CacheFlushManager.sv
add_files -norecurse rsd/Processor/Src/Decoder/MicroOp.sv
add_files -norecurse rsd/Processor/Src/Decoder/DecodedBranchResolver.sv
add_files -norecurse rsd/Processor/Src/Decoder/Decoder.sv
add_files -norecurse rsd/Processor/Src/Decoder/OpFormat.sv
add_files -norecurse rsd/Processor/Src/FloatingPointUnit/FP32PipelinedOther.sv
add_files -norecurse rsd/Processor/Src/FloatingPointUnit/FP32PipelinedMultiplier.sv
add_files -norecurse rsd/Processor/Src/FloatingPointUnit/FP32PipelinedFMAer.sv
add_files -norecurse rsd/Processor/Src/FloatingPointUnit/FP32PipelinedFMA.sv
add_files -norecurse rsd/Processor/Src/FloatingPointUnit/FPDivSqrtUnit.sv
add_files -norecurse rsd/Processor/Src/FloatingPointUnit/FP32PipelinedAdder.sv
add_files -norecurse rsd/Processor/Src/FloatingPointUnit/FPDivSqrtUnitIF.sv
add_files -norecurse rsd/Processor/Src/FloatingPointUnit/FP32DivSqrter.sv
